CU-33t2rv1: Play encoded audio file
projectNEWM/newm-artist-portal pull request #197
Opened 2023-03-07 13:35 UTC by dmkirshon

Includes:
 - Audio playback for song stream url on `Library` page with play/stop ability
   - Icon changes to play on song end
   - Audio playback stops on page change
   - Audio playback stops on filtered song

 - UI update for audio upload processing on Libray page, play button and song length table fields

Note:
 - Does not include the frontend update to load play button and song Length when song has finished processing on the backend. Requires manual
refresh of page.

 - Requires a CORS bypass for audio playback due to current access restrictions, used `CORS Unblock` chrome extension during development

 - Might be library bug or some other issue, when the audio player is created on Library page there is a noticable lag in dragging/moving the window browser around. Double checked with spotify web player and it has same issue, little bit of research led to disabling hardware acceleration to fix it... otherwise no real performance issue seen

2023-03-08 05:05 UTC, escobarjonatan requested changes

2023-03-08 12:16 UTC, dmkirshon commented on src/pages/home/library/Discography.tsx
> +
Strange, ok, I thought I tried using `useRef` and was running into an issue where even with the unmount disposal the player would not be removed and continue playing on other pages. Switched to useState to keep it within the component/page.

Is there a reason for having both `useState` and `useRef`? Should I use the `audioPlayerRef` for the pause, src, and play functionalities below that?

What do you mean by ensure access to the DOM element? Like for future visual audio player use/manipulation on other pages and you just meant a reference to the audio element created? Just from a javascript side of things, from what I understand the `new Audio()` works in the background as an in-memory javascript audio element, and doesn't actually add the audio element to the DOM, just technicalities but wanted to clarify.

2023-03-08 12:21 UTC, dmkirshon commented on src/pages/home/library/SongList.tsx
> +                          </Tooltip>
No problem was looking at all of the `SongList` page and going _man this should get refactored somehow..._ might need to revisit the whole file to separate and clean up the different features added post MVP. Unless it's seen as a worthy endeavor right now, let me know. For now will work off your suggestion Jonatan. Thank you!

2023-03-08 12:51 UTC, dmkirshon commented on src/pages/home/library/Discography.tsx
> +
Also, do you think I should create an `audioPlayer` util and refactor this out of `Discography`? It's simple enough now but I'm sure this is going to become a more robust feature, even if it is just for Artist previewing their own songs right now.

2023-03-08 13:38 UTC, dmkirshon commented on src/pages/home/library/SongList.tsx
> +                          </Tooltip>
Looking through,I assume the path without refactoring everything would be converting the 'songData.map' from an implicit return into one with '{}' and a return statement?

2023-03-09 04:33 UTC, escobarjonatan commented on src/pages/home/library/Discography.tsx
> +
>Is there a reason for having both useState and useRef? Should I use the audioPlayerRef for the pause, src, and play functionalities below that?
You could, i didnt test that locally 

State is usually used to hold a piece of information and ref is used to hold a reference to an actual element. Reading it again it does sound a bit confusing, sorry.
"The Audio() constructor creates and returns a new HTMLAudioElement which can be either attached to a document for the user to interact with and/or listen to, or can be used offscreen to manage and play audio" - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio).

>do you think I should create an audioPlayer util and refactor this out of Discography
Not sure juice is worth the squeeze here imo, i think it's okay to keep it here

2023-03-09 04:33 UTC, escobarjonatan commented on src/pages/home/library/SongList.tsx
> +                          </Tooltip>
I really like that last comment, if it's not too complicated to do, i would move it to its own component. If not, the variables will suffice

2023-03-13 12:44 UTC, dmkirshon commented on src/pages/home/library/Discography.tsx
> +
Makes sense, updated with useRef to handle the audio player element

2023-03-13 12:45 UTC, dmkirshon commented on src/pages/home/library/SongList.tsx
> +                          </Tooltip>
Updated with new `SongStreamPlaybackIcon` component

2023-03-13 21:03 UTC, escobarjonatan approved these changes

2023-03-14 13:22 UTC, merged