Feature/dsp-pricing-plan
projectNEWM/newm-artist-portal pull request #431
Opened 2023-12-04 12:52 UTC by dmkirshon

Adds the DSP Pricing Plan feature to NEWM Studio. The following tasks/components will need to be completed before merging the feature into the master branch:
- [X] [CU-86a1cktby: Create the DSP Pricing popup window](https://app.clickup.com/t/86a1cktby)
- [X] [CU-86a1ckn3y: Mint Song toggle button to trigger DSP pricing popup window](https://app.clickup.com/t/86a1ckn3y)
- [x] [CU-86a1ckn3y: Integrate endpoint to store DSP pricing plan user selection](https://app.clickup.com/t/86a1ckn3y)
- [X] [CU-86a1cktby: Integrate minting pricing endpoint into DSP pricing plan dialog](https://app.clickup.com/t/86a1cktby)

2023-12-07 09:11 UTC, newmskywalker commented
Task linked: [CU-86a1ckn3y Turning the Mint Song toggle button on should trigger the DSP Pricing popup window.](https://app.clickup.com/t/86a1ckn3y)

2023-12-07 09:11 UTC, newmskywalker commented
Task linked: [CU-86a1cktby Create the DSP Pricing popup window (within the Upload a Song form).](https://app.clickup.com/t/86a1cktby)

2023-12-07 15:45 UTC, dmkirshon commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +                    ? `$${Number(dspPriceUsd).toFixed(2)}/RELEASE`
Should I refactor to use the `formatPriceToDecimal` once merged?

2023-12-08 03:55 UTC, scandycuz requested changes
LGTM, but had a comment about the responsive sizing that I think would be good to address.

2023-12-08 03:55 UTC, scandycuz commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +            [theme.breakpoints.down("xl")]: {
The DSP pricing plan modal was vertically stacked on my laptop, even though the screen isn't that narrow. I'd change the theme's breakpoints to:

```
breakpoints: {
  values: {
    xs: 0,
    sm: 600,
    md: 960,
    lg: 1280,
    xl: 1600,
  },
},
```

and then change the responsive styling to change to a column on a `"lg"` screen and below, instead of `"xl"`. 

The responsive screen sizes were changed awhile ago to work better for the sample sales, but the sizes above are the Material UI defaults and probably work better.

<img width="1509" alt="Screen Shot 2023-12-07 at 7 40 17 PM" src="https://github.com/projectNEWM/newm-web/assets/5877597/f141f18b-7c0e-4099-8b60-6e3298093505">

2023-12-08 04:07 UTC, scandycuz commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +  readonly handleClose: () => void;
Just a syntax issue, but it's common practice to prefix function props with `on` and then have handlers inside of a component prefixed with `handle`. E.g. `<Example onClick={handleClick} />`.

Here's an article I found about it: https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364. It's mainly just helpful to avoid naming conflicts. E.g.

```
const Example = ({ onClose }) => {
  const handleClose = () => {
    // custom logic
  
    onClose()
  }
 
  ...
}
```
vs something like
```
const Example = ({ handleClose }) => {
  const _handleClose = () => {
    // custom logic
  
    handleClose()
  }
 
  ...
}
```

Also makes it easy to quickly know what is a prop.

2023-12-08 06:14 UTC, escobarjonatan approved these changes

2023-12-08 06:14 UTC, escobarjonatan commented on apps/studio/src/components/dspPricing/PricingPlanOption.tsx
> +import { Button, Typography } from "@newm-web/elements";
Typography should be imported from mui 🙃

2023-12-08 06:14 UTC, escobarjonatan commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +import { Dialog, Typography } from "@newm-web/elements";
import `Typography` from mui if possible

2023-12-08 06:14 UTC, escobarjonatan commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +                    ? `$${Number(dspPriceUsd).toFixed(2)}/RELEASE`
i think so, doesn't hurt. also we have somewhat similar solutions, i chose `parseFloat` over `Number` like you did here because in case we get `"1.233abcs"`, mine should output `"1.23"` vs in your case it would output to `NaN`.... small diff but think parseFloat is favored here in an edge case like this 🤷🏽‍♂️

2023-12-08 07:06 UTC, dmkirshon commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +            [theme.breakpoints.down("xl")]: {
I believe I set it so conservatively partly because of those breakpoints but also due to how the text was bunching up. I will make these breakpoint changes, make sure the panels remain horizontal per your recommendations, and tell product to watch out for discrepancies across the app since it will affect other responsive views.

2023-12-08 07:07 UTC, dmkirshon commented on apps/studio/src/components/dspPricing/PricingPlansDialog.tsx
> +  readonly handleClose: () => void;
Will create a refactor PR and include this.

2023-12-08 20:07 UTC, scandycuz approved these changes

2023-12-08 20:12 UTC, merged