feat: STUD-94 Add empty portfolio and transaction ui state
projectNEWM/newm-artist-portal pull request #534
Opened 2024-02-20 04:30 UTC by escobarjonatan

Portfolio:
![image](https://github.com/projectNEWM/newm-web/assets/11530120/965d0e96-971f-4f72-aabd-451ebb73a711)
Transactions:
![image](https://github.com/projectNEWM/newm-web/assets/11530120/fb2b4831-edf2-4a46-a2ef-7699456e03f8)

2024-02-20 13:45 UTC, dmkirshon requested changes
One minor change for order of Components loading.

2024-02-20 13:45 UTC, dmkirshon commented on apps/studio/src/pages/home/wallet/Portfolio.tsx
> +  }
I noticed, even though I have songs in my portfolio, navigating between transaction tab and portfolio tab, the `EmptyPortfolio` component displays first for a second and then the skeleton appears and then loads my portfolio. Should probably go straight to skeleton and then to portfolio.

2024-02-20 13:45 UTC, dmkirshon commented on apps/studio/src/pages/home/wallet/Portfolio.tsx
For our future note, we can let Denny know to add a Portfolio task or add a bug ticket, I noticed that a lot of data is being used to load the song album covers on the portfolio even though they are tiny. For reference 8 songs ended up being 24.5MB of data. 

![image](https://github.com/projectNEWM/newm-web/assets/86050631/db8bd8d2-6a74-452c-9d09-12c20580c8d1)

2024-02-20 15:36 UTC, escobarjonatan commented on apps/studio/src/pages/home/wallet/Portfolio.tsx
> +  }
ahh i see, fixed it by adding isSuccess to the custom thunk we have for this. Added isError in case we need it since i was there already

2024-02-20 15:43 UTC, escobarjonatan commented on apps/studio/src/pages/home/wallet/Portfolio.tsx
noted, this is interesting bc we should be getting those images in the correct size/format so those other images that are loading may be coming from somewhere else or something is going on.

2024-02-21 06:17 UTC, dmkirshon approved these changes
LGTM

2024-02-22 04:07 UTC, merged