STUD-180 Implement cover art agreement checkbox
projectNEWM/newm-artist-portal pull request #561
Opened 2024-03-14 04:22 UTC by escobarjonatan

![image](https://github.com/projectNEWM/newm-web/assets/11530120/2f2e390d-ec7b-4d2e-a139-5aa00f92cc1d)

2024-03-14 13:05 UTC, dmkirshon requested changes
LGTM, just one question about logic flow on cover art field updates

2024-03-14 13:05 UTC, dmkirshon commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +  const hasCoverArtChanged = values.coverArtUrl !== initialValues.coverArtUrl;
Is this logic, and the `useEffect` on line `164` below, based on the implication that if they have selected the checkbox and then replace their cover art, that the checkbox will reset each time they change their cover art? 

Right now it does the following:
1. Add image to field
2. Select checkbox to agree
3. Upload new/different image to field
4. Checkbox is still checked

2024-03-14 21:57 UTC, escobarjonatan commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +  const hasCoverArtChanged = values.coverArtUrl !== initialValues.coverArtUrl;
imo this is ok, we reset the status if it's not the same as it initially was. if they change it afterwards it doesn't matter since they've read the condition initially and agreed to it? i'll ask denny to check it out and see what he thinks of the flow

2024-03-15 04:08 UTC, scandycuz commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +  const hasCoverArtChanged = values.coverArtUrl !== initialValues.coverArtUrl;
I think either way could work. Resetting the box for each image would be more accurate, but the user may not notice that the box has been unchecked when they upload a new image and have to go through the process of seeing the error and resubmitting. If we leave it checked, that would be more convenient, and as Jonatan stated, could work because the user has confirmed they're aware of the guidelines.

2024-03-15 06:09 UTC, dmkirshon commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +  const hasCoverArtChanged = values.coverArtUrl !== initialValues.coverArtUrl;
Sounds good, as part of that initial question, I just wanted to understand if the intention was specifically for every time the field was touched or just when the song was already uploaded but still in edit mode within the Library. 

If once they checkmark the box, it's seen as acknowledged, I'm good with keeping the logic as is. With the way the logic flows they still have to acknowledge the guidelines again if they update the cover art in an upload/re-submit mode anyway.

2024-03-15 06:15 UTC, dmkirshon approved these changes
I don't believe the logic change for re-acknowledging the cover art message when the user switches the cover art multiple times on initial Song upload should be a blocker for pushing this PR through, if required by Product another task to update the logic can be created to address this UX.

2024-03-22 21:37 UTC, merged