STUD-223: Add country to signup flow and make it editable in profile
projectNEWM/newm-artist-portal pull request #609
Opened 2024-05-03 04:03 UTC by escobarjonatan

https://github.com/projectNEWM/newm-web/assets/11530120/48f6a8ae-190a-4949-9cae-efd8c4c019e6

2024-05-03 04:06 UTC, escobarjonatan commented on packages/elements/src/lib/styled/NoResultsText.ts
> +  bottom: -52px;
For some strange reason, i am not sure why this hadn't been an issue before, but we are placing this absolute to the relative field(dropdown) but were not setting the place of where we wanted it. It worked in the scenarios we are using it in currently assuming bc of the containers we are wrapping it on? anyway, i tried to use the dropdown field as it was and the results came out fine but the no results box was somewhere else lol I tested out the other places to make sure this still worked as we intended and it does. The 52 offsets the input

2024-05-03 13:20 UTC, dmkirshon requested changes
Running into an issue with form values not persisting on the `create-profile` flow causing an endless user loop. Also a few other comments and corrections noted.

2024-05-03 13:20 UTC, dmkirshon commented on apps/studio/src/pages/createProfile/CreateProfile.tsx
> +              path: "what-is-your-loocation",
Was wondering if I was having a stroke... just looks like one too many o's in loooocation. Was sending me to a black page with invitations pending as the `!location` redirect is correct https://github.com/projectNEWM/newm-web/blob/17f95e91fcf7cbee7f759a691325e81f804cf26b/apps/studio/src/pages/home/Home.tsx#L35-L38


![image](https://github.com/projectNEWM/newm-web/assets/86050631/e37d689c-d99d-465b-ac10-4839d0baaa7f)

2024-05-03 13:20 UTC, dmkirshon commented on apps/studio/src/pages/createProfile/SelectLocation.tsx
> +        Finally, what is your country of residence?
The UX seems ok for our initial release but if we end up having more required details for them to fill out we might want to think of a different UX as this seems pretty jarring to just redirect to this page. It might just be the word "Finally" for existing users that's catching me off guard...

2024-05-03 13:20 UTC, dmkirshon commented on apps/studio/src/common/formUtils.ts
> +      .test("is-location", "You need to type or select one", (location) =>
Will this test ever be reached? We give them set location values and they have to select one. Trying to manually type something in the field just clears out if it doesn't select a value.

2024-05-03 13:20 UTC, dmkirshon commented on apps/studio/src/pages/createProfile/CreateProfile.tsx
I don't think I have a `location` set in my Profile. I keep getting redirected to the `create-profile/location` page, it seems like my location value in the create-profile flow doesn't ever get updated so I'm stuck in an endless loop. I haven't been able to pinpoint why my selected `location` value doesn't persist. `updateInitialProfile` is called but it doesn't include the `location` value in the update. 

When I select next and move from the `create-profile/location` page to `create-profile/complete` it looks like formik loses `FormikContext: {values:  }`. It persists when starting on the initial `create-profile` route, but starting on any of the other routes leads into the same issue where the next button clears `FormikContext: {values}`. This might be a bug within `WizardForm` and how things persist when entering the form midway? 

I need to do a bit more digging if you don't see this on your end. If you already have a saved `location` in your Profile, have you chosen a different country on the `create-profile/location` page from the one that is in your Profile and seen it persist?

2024-05-03 13:57 UTC, escobarjonatan commented on apps/studio/src/pages/createProfile/CreateProfile.tsx
> +              path: "what-is-your-loocation",
i knew i should have copy/paste lol good catch, adding 3 more o's

2024-05-03 14:01 UTC, escobarjonatan commented on apps/studio/src/pages/createProfile/SelectLocation.tsx
> +        Finally, what is your country of residence?
This will be the experience for a few of them, most will go through the signup flow. This should be ok

2024-05-03 14:02 UTC, escobarjonatan commented on apps/studio/src/common/formUtils.ts
> +      .test("is-location", "You need to type or select one", (location) =>
i copied it from roles, but you are right, it doesn't seem to get to it, i'll remove it

2024-05-03 14:41 UTC, escobarjonatan commented on apps/studio/src/pages/createProfile/CreateProfile.tsx
Very nice find, see i already had my location setup before this and tried to mock it without it but clearly didnt work lol I found out the issue(i think). In your case, you didn't have your location but you had your name/last/role and other stuff. so it went like this:
1. location page -> 2. all set (submit) -> 3. profile page -> 4. redirect to create-profile page


on 1, the form had the initial values to empty strings(name/last/role) so when submitting your location, you were also submitting empty values for the rest, meaning that you were setting your name to "" and that's where the loop began. I fixed this by changing the initial values to the profile query if it had any of those values it would use them as the initial values. Here's a video to demo this flow. I temporarily made the input on Profile a text and removed validation for this demo only: 

https://github.com/projectNEWM/newm-web/assets/11530120/948c2d96-df65-4b37-a3f8-2a617c3218ba

2024-05-03 16:39 UTC, dmkirshon approved these changes
LGTM, looks like the flow is working now!

2024-05-06 05:00 UTC, scandycuz approved these changes

2024-05-06 18:31 UTC, merged