Chore: Add individual pipelines for production deployment
projectNEWM/newm-artist-portal pull request #664
Opened 2024-05-29 16:47 UTC by escobarjonatan

## Changes

- Add individual pipeline workflows to maintain customization flexibility
- Add todo comments that need work items outside of my permissions

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +        run: echo "COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.1 /lambda-adapter /opt/extensions/lambda-adapter" >> apps/marketplace/Dockerfile
I know we have added docker file/config to tools and wallet but this might be something we need to do for marketplace.

CC: @scandycuz @jayvaznewm

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO }} #TODO: These might need the marketplace role or modify this to be a generic role
@jayvaznewm  At the moment we have secret `AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO` and the name itself has `STUDIO` i was thinking we can either create a separate arn role to give marketplace only access. The other option is to create a generic role for all of our apps since most need the same?

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-mobile-wallet-connector.yml
> +          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO }} #TODO: These might need the mobile-wallet-connector role or modify this to be a generic role
@jayvaznewm  At the moment we have secret `AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO` and the name itself has `STUDIO` i was thinking we can either create a separate arn role to give wallet only access. The other option is to create a generic role for all of our apps since most need the same?

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-tools.yml
> +          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO }} #TODO: These might need the tools role or modify this to be a generic role
@jayvaznewm  At the moment we have secret `AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO` and the name itself has `STUDIO` i was thinking we can either create a separate arn role to give tools only access. The other option is to create a generic role for all of our apps since most need the same?

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release.yml
> +# TODO: DELETE THIS FILE AFTER INDIVIDUAL PIPELINES ARE UPDATED WITH THE NEW WORKFLOW
@jayvaznewm @scandycuz i assume that once github actions are updated to include these individual workflows this file will not longer be needed and therefore can be deleted

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-mobile-wallet-connector.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NEWM_STUDIO_WEBHOOK }} #TODO: This should be a mobile-wallet-connector webhook
Currently we have `SLACK_NEWM_STUDIO_WEBHOOK` that is setup to send notifications to our `newm-studio` channel. We have a channel called `#newm-wallet-connector` that we would like to send notifications related to deployment so a new variable like `SLACK_NEWM_MOBILE_WALLET_CONNECTOR_WEBHOOK` is created and configured. 

Not sure who has the power to do that @scandycuz @jayvaznewm

2024-05-29 16:58 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-tools.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NEWM_STUDIO_WEBHOOK }} #TODO: This should be a tools webhook
Currently we have `SLACK_NEWM_STUDIO_WEBHOOK` that is setup to send notifications to our `newm-studio` channel. We have a channel called `#newm-tools` that we would like to send notifications related to deployment so a new variable like `SLACK_NEWM_TOOLS_WEBHOOK` is created and configured. 

Not sure who has the power to do that @scandycuz @jayvaznewm

2024-05-29 17:39 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +        run: echo "COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.1 /lambda-adapter /opt/extensions/lambda-adapter" >> apps/marketplace/Dockerfile
i see we have it in marketplace, please ignore this comment. I'll remove the TODO comment above

2024-05-29 17:40 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release.yml
> +# TODO: DELETE THIS FILE AFTER INDIVIDUAL PIPELINES ARE UPDATED WITH THE NEW WORKFLOW
Will remove as part of this PR so it doesnt cause a double trigger

2024-05-29 17:56 UTC, scandycuz requested changes
Looking good. Left some optional comments about removing unneccesary code, but some of the other changes are necessary for the deploys to be successful. Also, all of the build args will need to be passed in the `.github/workflows/cdk/bin/deploy.ts` file (through the `buildArgs` option) and exposed in the Dockerfiles using `ARG {variableName}`.

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          VITE_ENV: production
The code from line `16` to `28` can be removed, since the build occurs in the Docker container now

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          APPNAME=marketplace APPID=Marketplace QUALIFIER=Studio NEXT_PUBLIC_ENV=production NEXT_PUBLIC_RECAPTCHA_SITE_KEY_STAGING=${{ secrets.RECAPTCHA_SITE_KEY_PROD }} npm run --prefix .github/work
The `NEXT_PUBLIC_RECAPTCHA_SITE_KEY_STAGING` variable name should be updated to `NEXT_PUBLIC_RECAPTCHA_SITE_KEY_PROD`.

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-mobile-wallet-connector.yml
> +          VITE_ENV: production
Same with the other workflow, lines `16` to `24` can be removed, as it will just increase the deployment time.

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-mobile-wallet-connector.yml
> +
The `NEXT_PUBLIC_RECAPTCHA_SITE_KEY_STAGING` variable name should be updated to `NEXT_PUBLIC_RECAPTCHA_SITE_KEY_PROD` here as well.

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-tools.yml
> +          VITE_ENV: production
Lines `16` through `23` can be removed.

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          APPNAME=marketplace APPID=Marketplace QUALIFIER=Studio NEXT_PUBLIC_ENV=production NEXT_PUBLIC_RECAPTCHA_SITE_KEY_STAGING=${{ secrets.RECAPTCHA_SITE_KEY_PROD }} npm run --prefix .github/work
The `env` package could probably abstract this so that it's only necessary to reference a `NEXT_PUBLIC_RECAPTCHA_SITE_KEY` env variable, but currently staging and prod are referenced separately

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-mobile-wallet-connector.yml
> +          VITE_ENV: production
The lines changed since this comment, but essentially, the build that occurs outside of the Docker container is no longer necessary.

2024-05-29 17:56 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-mobile-wallet-connector.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NEWM_STUDIO_WEBHOOK }} #TODO: This should be a mobile-wallet-connector webhook
I should be able to update that.

2024-05-29 23:16 UTC, jayvaznewm commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO }} #TODO: These might need the marketplace role or modify this to be a generic role
`AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO` deploys into the "studio" AWS account, `AWS_GITHUB_DEPLOY_ROLE_ARN_GARAGE` deploys into the "garage" AWS account.

In this instance "studio" refers to the stage (dev, staging, prod) not the app (studio, marketplace, mobile-wallet)

Do you think marketplace and the studio app require separate roles ?

2024-05-30 01:38 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO }} #TODO: These might need the marketplace role or modify this to be a generic role
Makes sense that "STUDIO" is referring to the production environment. I imagine we should probably standardize on "staging" and "prod" (or "production") to reference the environments in the future, but it's not a huge priority to update the naming here.

2024-05-30 02:06 UTC, scandycuz commented on .github/workflows/aws-hosting-deploy-published-release-newm-tools.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NEWM_STUDIO_WEBHOOK }} #TODO: This should be a tools webhook
Added the Slack hook url environtment secrets for the tools and mobile wallet connector apps. The  tools secret name is `SLACK_NEWM_TOOLS_WEBHOOK` and the mobile wallet connector app secret name is `SLACK_NEWM_MOBILE_WALLET_CONNECTOR_WEBHOOK`.

2024-05-30 02:32 UTC, escobarjonatan commented on .github/workflows/aws-hosting-deploy-published-release-newm-marketplace.yml
> +          APPNAME=marketplace APPID=Marketplace QUALIFIER=Studio NEXT_PUBLIC_ENV=production NEXT_PUBLIC_RECAPTCHA_SITE_KEY_STAGING=${{ secrets.RECAPTCHA_SITE_KEY_PROD }} npm run --prefix .github/work
Yea, that's something we can do in the future

2024-05-30 03:38 UTC, scandycuz approved these changes

2024-05-30 03:45 UTC, merged