STUD-287: Update limit on song description characters
projectNEWM/newm-artist-portal pull request #703
Opened 2024-07-29 00:48 UTC by escobarjonatan

2024-07-29 09:44 UTC, dmkirshon requested changes
LGTM, just requesting a change in the character count placement to by in sync with error message.

2024-07-29 09:44 UTC, dmkirshon commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +          </Typography>
The error message appearing and nudging the character count is a little jarring
![image](https://github.com/user-attachments/assets/a611c3ec-f060-4768-9cd7-70d546dbcedb)

Can we move it within the `TextAreaField.tsx` to `TextArea.tsx` to be in line with the error message?
https://github.com/projectNEWM/newm-web/blob/5d6cab6ab395621537b8facdcd0ee4b73ac9cbf2/packages/elements/src/lib/TextArea.tsx#L168-L169

2024-07-30 01:04 UTC, scandycuz commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +          </Typography>
Good catch, it would be ideal to have these on the same line.

2024-07-30 02:53 UTC, escobarjonatan commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +          </Typography>
awk, tested both but not together or didn't notice it. Fixed it now:

![image](https://github.com/user-attachments/assets/98090f7d-249e-44ab-9ec2-492e4a90aed8)
![image](https://github.com/user-attachments/assets/59acf5c7-8c8c-4de6-8da5-9f64a10f1b9c)

2024-07-30 09:57 UTC, dmkirshon approved these changes
LGTM, just a question about the character count prop.

2024-07-30 09:57 UTC, dmkirshon commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +            currentCharacterCount={ values.description?.length }
Not a show stopper, but couldn't this be obtained within the `TextArea.tsx` through the `value` prop? Is there a reason to prop drill it?

2024-07-31 03:15 UTC, escobarjonatan commented on apps/studio/src/pages/home/uploadSong/BasicSongDetails.tsx
> +            currentCharacterCount={ values.description?.length }
I thought about it but think this is a cleaner solution since it can give the flexibility to omit characters if needed? for example, you could use a text area with validation to only count words over text and this gives you the ability to add your own custom logic. You also have controlled vs uncontrolled inputs and think destructuring the value and adding it would interfere with uncontrolled

2024-07-31 03:15 UTC, merged